export const LoginType = {
    REQUEST_LOGIN: "REQUEST_LOGIN",
    REQUEST_LOGIN_SUCCESS: "REQUEST_LOGIN_SUCCESS",
    REQUEST_LOGIN_FAILED: "REQUEST_LOGIN_FAILED",
}
export const HistoryType = {
    REQUEST_HISTORY: "REQUEST_HISTORY",
    REQUEST_HISTORY_SUCCESS: "REQUEST_HISTORY_SUCCESS",
    REQUEST_HISTORY_FAILED: "REQUEST_HISTORY_FAILED",
}
export const GetInfoItemType = {
    REQUEST_INFO_ITEM: "REQUEST_INFO_ITEM",
    REQUEST_INFO_ITEM_SUCCESS: "REQUEST_INFO_ITEM_SUCCESS",
    REQUEST_INFO_ITEM_FAILED: "REQUEST_INFO_ITEM_FAILED",
}
export const InfoUserType = {
    REQUEST_INFO_USER: "REQUEST_INFO_USER",
    REQUEST_INFO_USER_SUCCESS: "REQUEST_INFO_USER_SUCCESS",
    REQUEST_INFO_USER_FAILED: "REQUEST_INFO_USER_FAILED",
}