
target 'DemoAndroidProject' do
   pod 'React', :path => '../node_modules/react-native'
   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
   pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'
end